_BASE_: ["../single_timeframe.yml", "../models/pointpillar.yml"]

TAG: "lss"
EVA_DIR: "output_dir/lss"
# EVALUATION: False

GPUS: [0, 1]
EPOCHS: 40
BATCHSIZE: 6
N_WORKERS: 6
VALID_FREQ: 1.0 
GRAD_NORM_CLIP: 10
CKPT_PATH: None
# CKPT_PATH: '/home/master/10/cytseng/fiery/tensorboard_logs/lss_mm_cam_6_imgSize_336_720_segLoss/version_0/checkpoints/epoch=4-step=11719.ckpt'

SEMANTIC_SEG:
  NUSCENE_CLASS: True

DATASET:
  DATAROOT: "/home/master/10/cytseng/data/sets/nuscenes/"
  FILTER_INVISIBLE_VEHICLES: True
  VERSION: "v1.0-trainval"
  TRAINING_SAMPLES: -1
  VALIDATING_SAMPLES: 2000

LIFT:
  X_BOUND: [-50.0, 50.0, 0.5] # Â Forwards
  Y_BOUND: [-50.0, 50.0, 0.5] # Sides
  Z_BOUND: [-10.0, 10.0, 20.0] # Height

IMAGE:
  N_CAMERA: 6
  FINAL_DIM: [224, 480]
  RESIZE_SCALE: 0.3
  TOP_CROP: 46

LOSS:
  SEG_USE: True

OBJ:
  HEAD_NAME: "mm"
